name: Update Events

on:
  repository_dispatch:
    types: [update_events]

jobs:
  update-events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update events file
        run: |
          echo '${{ github.event.client_payload.events }}' > events.json
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add events.json
          git commit -m "Update events data"
          git push 